version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    container_name: backend_service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: frontend_service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production