FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    libxrender1 libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --upgrade pip

# Copy backend requirements and install dependencies
COPY backend/req.txt .
RUN pip install -r req.txt

# Copy the engine package so it can be installed in editable mode
COPY engine/ ./engine/
# RUN pip install -r ./engine/req.txt
RUN pip install -e ./engine/

# Copy the rest of the backend source code
COPY backend/ ./backend/

# Expose port 8000 for FastAPI
EXPOSE 8000

WORKDIR /app/backend

# Run the FastAPI app using uvicorn
CMD ["python", "main.py"]