import os

GOOGLE_CLOUD_PROJECT_API_KEY = os.environ.get("GOOGLE_CLOUD_PROJECT_API_KEY")
SMILES_API_ENDPOINT = os.environ.get("SMILES_API_ENDPOINT")
SMILES_INDEX_ENDPOINT = os.environ.get("SMILES_INDEX_ENDPOINT")
SMILES_DEPLOYED_INDEX_ID = os.environ.get("SMILES_DEPLOYED_INDEX_ID")
PSMILES_API_ENDPOINT = os.environ.get("PSMILES_API_ENDPOINT")
PSMILES_INDEX_ENDPOINT = os.environ.get("PSMILES_INDEX_ENDPOINT")
PSMILES_DEPLOYED_INDEX_ID = os.environ.get("PSMILES_DEPLOYED_INDEX_ID")
CHROMADB_PERSISTENT_PATH = os.environ.get("CHROMADB_PERSISTENT_PATH")
CHROMADB_SMILES_DB_NAME = os.environ.get("CHROMADB_SMILES_DB_NAME")
CHROMADB_PSMILES_DB_NAME = os.environ.get("CHROMADB_PSMILES_DB_NAME")